name: spd_notifier
description: "SPD Notify."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  cloud_firestore: ^5.1.0
  connectivity_plus: ^6.0.3
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.spd.spd_notifier
        pluginClass: SpdNotifierPlugin
      ios:
        pluginClass: SpdNotifierPlugin
